name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build the JAR file
        run: |
          chmod +x mvnw || true
          if [ -f mvnw ]; then ./mvnw clean package -DskipTests; else mvn clean package -DskipTests; fi

      - name: Build and Push Docker Image
        run: |
          docker build --platform linux/arm64 -t leodavintxi/easyplusoracle:latest .
          docker push leodavintxi/easyplusoracle:latest

      - name: Desplegar en Oracle Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo lsof -t -i:3000 | xargs sudo kill -9 || true
            docker stop easyplus || true
            docker rm -f easyplus || true
            docker rmi -f leodavintxi/easyplusoracle:latest || true
            docker pull leodavintxi/easyplusoracle:latest
            docker run -d -p 3000:3000 --name easyplus \
              -e DB_URL=${{ secrets.DB_URL }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e SECURITY_USER=${{ secrets.SECURITY_USER }} \
              -e SECURITY_PASSWORD=${{ secrets.SECURITY_PASSWORD }} \
              -e SPRING_PROFILES_ACTIVE=prod \
              leodavintxi/easyplusoracle:latest
